---
name: docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        folder:
          - v3.14
          - v3.13
          - v3.12
          - v3.11
          - v3.10
          - v3.9
          - v3.8
          - v3.7
          - v3.6
          - latest

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@v2

      - name: Define version
        id: prepare
        run: |
          TAG=${{ matrix.folder }}

          if [[ "${TAG}" =~ ^v[0-9._-]+$ ]]; then
            TAG=${TAG#v}
          fi

          echo ::set-output name=tag::${TAG}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: |
            webhippie/alpine
            quay.io/webhippie/alpine
          labels: |
            org.opencontainers.image.vendor=Webhippie
            maintainer=Thomas Boerger <thomas@webhippie.de>

      - name: Setup QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1

      - name: Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Hub login
        id: login1
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Quay login
        id: login2
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build amd64
        id: amd64
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ${{ matrix.folder }}/
          file: ${{ matrix.folder }}/Dockerfile.amd64
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            webhippie/alpine:${{ steps.prepare.outputs.tag }}-amd64
            quay.io/webhippie/alpine:${{ steps.prepare.outputs.tag }}-amd64
          cache-from: type=gha,scope=buildkit-${{ matrix.folder }}-amd64
          cache-to: type=gha,mode=max,scope=buildkit-${{ matrix.folder }}-amd64

      - name: Build arm64
        id: arm64
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ${{ matrix.folder }}/
          file: ${{ matrix.folder }}/Dockerfile.arm64
          platforms: linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            webhippie/alpine:${{ steps.prepare.outputs.tag }}-arm64
            quay.io/webhippie/alpine:${{ steps.prepare.outputs.tag }}-arm64
          cache-from: type=gha,scope=buildkit-${{ matrix.folder }}-arm64
          cache-to: type=gha,mode=max,scope=buildkit-${{ matrix.folder }}-arm64

      - name: Build armv6
        id: armv6
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ${{ matrix.folder }}/
          file: ${{ matrix.folder }}/Dockerfile.armv6
          platforms: linux/arm/v6
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            webhippie/alpine:${{ steps.prepare.outputs.tag }}-armv6
            quay.io/webhippie/alpine:${{ steps.prepare.outputs.tag }}-armv6
          cache-from: type=gha,scope=buildkit-${{ matrix.folder }}-armv6
          cache-to: type=gha,mode=max,scope=buildkit-${{ matrix.folder }}-armv6

      - name: Hub manifest
        id: manifest1
        uses: actionhippie/manifest@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          platforms: linux/amd64,linux/arm64,linux/arm/v6
          template: webhippie/alpine:${{ steps.prepare.outputs.tag }}-ARCH
          target: webhippie/alpine:${{ steps.prepare.outputs.tag }}
          ignore_missing: true

      - name: Quay manifest
        id: manifest2
        uses: actionhippie/manifest@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          platforms: linux/amd64,linux/arm64,linux/arm/v6
          template: quay.io/webhippie/alpine:${{ steps.prepare.outputs.tag }}-ARCH
          target: quay.io/webhippie/alpine:${{ steps.prepare.outputs.tag }}
          ignore_missing: true

...
